services:
  app:
    container_name: blockchain-container
    image: blockchain
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    env_file:
      - .env
    volumes:
      - ".${SECURITY_CERT_PATH}:${SECURITY_CERT_PATH}"
      - ".${SECURITY_KEY_PATH}:${SECURITY_KEY_PATH}"